name: kartjis_mobile_organizer
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.5.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.15
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  http: ^1.2.1
  http_interceptor: ^2.0.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.1
  internet_connection_checker_plus: ^2.2.0
  intl: any
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.1
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  import_sorter: ^4.6.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Titillium Web
      fonts:
        - asset: fonts/TitilliumWeb-Bold.ttf
    - family: GTWalsheimPro
      fonts:
        - asset: fonts/GTWalsheimPro-Black.ttf
        - asset: fonts/GTWalsheimPro-Bold.ttf
        - asset: fonts/GTWalsheimPro-Light.ttf
        - asset: fonts/GTWalsheimPro-Medium.ttf
        - asset: fonts/GTWalsheimPro-Regular.ttf
        - asset: fonts/GTWalsheimPro-Thin.ttf
